export enum EAPIFunctionErrorTypes {
  VERIFIER_VERIFICATION_TASK_ASSIGNED_TO_OTHERS = 'VERIFIER_VERIFICATION_TASK_ASSIGNED_TO_OTHERS',
  USER_CREDENTIAL_INVALID = 'USER_CREDENTIAL_INVALID',
  USER_ACCOUNT_LOCKED = 'USER_ACCOUNT_LOCKED',
  // this can be any other user account related exceptions that we do not want to expose the details to the client
  AUTH_CHECK_SESSION_INVALID = 'AUTH_CHECK_SESSION_INVALID',
  MFA_INVALID_CODE = 'MFA_INVALID_CODE',
  MFA_MOBILE_NUMBER_USED = 'MFA_MOBILE_NUMBER_USED',
}
